import streamlit as st
from bokeh.embed import file_html
from bokeh.resources import CDN
from bokeh.plotting import output_file, save
import os

def display_bokeh_plot():
    # Generate Bokeh plot
    os.system('python bokeh_plot.py')

    # Read the HTML file generated by Bokeh
    with open("bokeh_plot.html", "r") as file:
        bokeh_html = file.read()

    # Display the Bokeh plot in Streamlit
    st.components.v1.html(bokeh_html, height=600, width=800)

st.title("Interactive Bokeh Plot in Streamlit")
display_bokeh_plot()
