[secrets]
GDRIVE_URL_SAMPLE_DATA = "https://drive.google.com/drive/folders/1a_bOslQ2Sjh4Jm94xAh6_bcYmGeAmEPj?usp=sharing"
GDRIVE_URL_DINOBLOOM_S = "https://drive.google.com/file/d/1iy3K1E-lhef6iE26ewzMYPG8mwknkMHa/view?usp=sharing"
GDRIVE_URL_DINOBLOOM_B = "https://drive.google.com/file/d/1vs1DDpl3O93C_AwLLjaYSiKAI-N_Uitc/view?usp=sharing"
GDRIVE_URL_DINOBLOOM_L = "https://drive.google.com/file/d/1eXGCZzDez85ip4LEX1VIHe4TBmpuXaHY/view?usp=sharing"
GDRIVE_URL_DINOBLOOM_G = "https://drive.google.com/file/d/1-C-ip2qrKsp4eYBebw3ItWuu63crUitE/view?usp=sharing"
